name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: './go.mod'

    - name: Build
      run: go build -v ./...
    
    - name: Windows Build Test
      run: |
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w"
        GOOS=windows GOARCH=386 go build -ldflags="-s -w"
        GOOS=windows GOARCH=arm64 go build -ldflags="-s -w"
    
    - name: Darwin Build Test
      run: |
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w"
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w"
    
    - name: Linux Build Test
      run: |
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w"
        GOOS=linux GOARCH=386 go build -ldflags="-s -w"
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w"
        GOOS=linux GOARCH=riscv64 go build -ldflags="-s -w"
        GOOS=linux GOARCH=loong64 go build -ldflags="-s -w"

    - name: Test
      run: go test -v ./...

    - name: Test Race
      run: go test -race -v ./...
