# testing
title = "TOML examples"

int_value = 42
float_value = 3.1415

is_active = true
created_at = 2025-12-12T00:00:00+09:00

multiline_string = """
これは
複数行の
文字列です。
"""

colors = ["red", "green", "blue"]

# arrays
[[servers]]
name = "alpha"
ip = "192.168.1.1"

[[servers]]
name = "beta"
ip = "192.168.1.2"

[database]
server = "127.0.1.1"
ports = [ 8001, 8002, 8003 ]
connection_max = 5000
enabled = true

# nested
[owner]
name = "scc"
dob = 2000-07-01T12:00:00Z

[owner.contact]
address = "test"
phone = "+xx-xxx-xxx-xxxx"
